targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        generate_for:
          - lib/**
      auto_route_generator:autoRouteGenerator:
        enabled: true
        generate_for:
          - lib/**
      json_serializable:json_serializable:
        enabled: true
        generate_for:
          - lib/**


